### ISSUE TITLE
How to configure irssi to spew logs in the required format?

### ISSUE THREAD

**Issue by dbolser** [kivy/irssi2html#1]
I'm reading the logging section here:
http://www.irssi.org/documentation/manual

but I can't see how to get the networkname and channel variables into the log file name

**Comment by Link-Satonaka** [comment]
I think maybe this issue should be, "get rid of required format", since this is rather obtuse. I get that this is probably a personal tool you've the dev decided to share, but hey, you put it out there, I'ma bring up the issues :)

**Comment by dessant** [comment]
Yes, this code can be considered abandoned for now.
